name: Deploy Simples

on:
  push:
    branches:
      - main  # ou master, se for seu branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositÃ³rio
        uses: actions/checkout@v3

      - name: Build Simples
        run: echo "Deploy bem-sucedido"

      - name: Criar artefato
        run: echo "Arquivo de sucesso" > sucesso.txt

      - name: Upload do artefato
        uses: actions/upload-artifact@v3
        with:
          name: deploy-sucesso
          path: sucesso.txt
